const $=s=>document.querySelector(s);let jobs=[],currentUser=null,quickFilter='all';
const authView=$('#authView'),appView=$('#appView'),jobsList=$('#jobsList'),dialog=$('#jobDialog');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const labelStatus=s=>({new:'New',to_schedule:'To schedule',scheduled:'Scheduled',in_progress:'In progress',waiting:'Waiting / follow-up',completed:'Completed'}[s]||s);
function localDate(){const d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)}
async function init(){const{data:{session}}=await supabaseClient.auth.getSession();setSession(session);supabaseClient.auth.onAuthStateChange((_e,s)=>setSession(s));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
async function setSession(session){currentUser=session?.user||null;authView.classList.toggle('hidden',!!currentUser);appView.classList.toggle('hidden',!currentUser);if(currentUser)await loadJobs()}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();$('#authMessage').textContent='';const{error}=await supabaseClient.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)$('#authMessage').textContent=error.message});
$('#signUpBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<6){$('#authMessage').textContent='Enter an email and password (minimum 6 characters).';return}const{error}=await supabaseClient.auth.signUp({email,password});$('#authMessage').textContent=error?error.message:'Account created. Check your email if confirmation is required.'};
$('#signOutBtn').onclick=()=>supabaseClient.auth.signOut();
async function loadJobs(){const{data,error}=await supabaseClient.from('jobs').select('*').order('scheduled_date',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false});if(error){jobsList.innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}jobs=data||[];render()}
function filtered(){const q=$('#searchInput').value.toLowerCase().trim(),status=$('#statusFilter').value,today=localDate();return jobs.filter(j=>{if(status&&j.status!==status)return false;if(quickFilter==='today'&&j.scheduled_date!==today)return false;if(quickFilter==='unscheduled'&&j.scheduled_date)return false;if(quickFilter==='completed'&&j.status!=='completed')return false;if(q&&!`${j.title} ${j.customer_name} ${j.suburb} ${j.address_line} ${j.description}`.toLowerCase().includes(q))return false;return true})}
function render(){const today=localDate();$('#countAll').textContent=jobs.length;$('#countToday').textContent=jobs.filter(j=>j.scheduled_date===today&&j.status!=='completed').length;$('#countUnscheduled').textContent=jobs.filter(j=>!j.scheduled_date&&j.status!=='completed').length;$('#countCompleted').textContent=jobs.filter(j=>j.status==='completed').length;const rows=filtered();jobsList.innerHTML=rows.length?rows.map(j=>`<article class="job-card" data-id="${j.id}"><div class="job-top"><div><div class="job-title">${esc(j.title)}</div><div class="muted">${esc(j.customer_name||'No customer')}${j.suburb?` · ${esc(j.suburb)}`:''}</div></div><span class="chip">${esc(labelStatus(j.status))}</span></div><div class="chips">${j.scheduled_date?`<span class="chip">📅 ${esc(j.scheduled_date)}${j.scheduled_start?` ${esc(j.scheduled_start.slice(0,5))}`:''}</span>`:'<span class="chip">Unscheduled</span>'}${j.priority!=='normal'?`<span class="chip">${esc(j.priority)}</span>`:''}${j.estimated_minutes?`<span class="chip">⏱ ${j.estimated_minutes} min</span>`:''}</div></article>`).join(''):'<div class="empty">No jobs here yet.</div>';document.querySelectorAll('.job-card').forEach(c=>c.onclick=()=>openJob(jobs.find(j=>j.id===c.dataset.id)))}
$('#searchInput').oninput=render;$('#statusFilter').onchange=render;document.querySelectorAll('.stat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.stat').forEach(x=>x.classList.remove('active'));b.classList.add('active');quickFilter=b.dataset.filter;render()});
function openJob(j=null){$('#jobForm').reset();$('#jobId').value=j?.id||'';$('#jobDialogTitle').textContent=j?'Edit job':'New job';$('#deleteJobBtn').classList.toggle('hidden',!j);const fields={jobTitle:'title',customerName:'customer_name',customerPhone:'customer_phone',addressLine:'address_line',suburb:'suburb',postcode:'postcode',description:'description',notes:'notes',status:'status',priority:'priority',scheduledDate:'scheduled_date',scheduledStart:'scheduled_start',estimatedMinutes:'estimated_minutes'};if(j)for(const[id,key]of Object.entries(fields))$('#'+id).value=j[key]??'';else{$('#status').value='new';$('#priority').value='normal'}dialog.showModal()}
$('#newJobBtn').onclick=()=>openJob();$('#closeJobBtn').onclick=()=>dialog.close();
$('#jobForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#jobId').value,payload={user_id:currentUser.id,title:$('#jobTitle').value.trim(),customer_name:$('#customerName').value.trim()||null,customer_phone:$('#customerPhone').value.trim()||null,address_line:$('#addressLine').value.trim()||null,suburb:$('#suburb').value.trim()||null,postcode:$('#postcode').value.trim()||null,description:$('#description').value.trim()||null,notes:$('#notes').value.trim()||null,status:$('#status').value,priority:$('#priority').value,scheduled_date:$('#scheduledDate').value||null,scheduled_start:$('#scheduledStart').value||null,estimated_minutes:Number($('#estimatedMinutes').value)||null};payload.completed_at=payload.status==='completed'?new Date().toISOString():null;const q=id?supabaseClient.from('jobs').update(payload).eq('id',id):supabaseClient.from('jobs').insert(payload);const{error}=await q;if(error){alert(error.message);return}dialog.close();await loadJobs()});
$('#deleteJobBtn').onclick=async()=>{const id=$('#jobId').value;if(!id||!confirm('Delete this job?'))return;const{error}=await supabaseClient.from('jobs').delete().eq('id',id);if(error){alert(error.message);return}dialog.close();await loadJobs()};
init();
