const $=s=>document.querySelector(s);let jobs=[],currentUser=null,quickFilter='all',pinUnlocked=false;
const AUTH_REDIRECT_URL='https://appsbysam.github.io/PowerUp/';
const authView=$('#authView'),pinView=$('#pinView'),appView=$('#appView'),jobsList=$('#jobsList'),dialog=$('#jobDialog'),pinDialog=$('#pinDialog');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const labelStatus=s=>({new:'New',to_schedule:'To schedule',scheduled:'Scheduled',in_progress:'In progress',waiting:'Waiting / follow-up',completed:'Completed'}[s]||s);const pinKey=id=>`powerup_pin_${id}`;
async function pinHash(pin,id){const data=new TextEncoder().encode(`PowerUp:${id}:${pin}`),buf=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function localDate(){const d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)}
async function init(){const{data:{session}}=await supabaseClient.auth.getSession();await setSession(session,true);supabaseClient.auth.onAuthStateChange((_e,s)=>setSession(s,false));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
async function setSession(session,initial=false){currentUser=session?.user||null;if(!currentUser){pinUnlocked=false;pinView.classList.add('hidden');appView.classList.add('hidden');authView.classList.remove('hidden');return}const hasPin=!!localStorage.getItem(pinKey(currentUser.id));if(initial&&hasPin&&!pinUnlocked){authView.classList.add('hidden');appView.classList.add('hidden');pinView.classList.remove('hidden');return}pinUnlocked=true;authView.classList.add('hidden');pinView.classList.add('hidden');appView.classList.remove('hidden');await loadJobs()}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();$('#authMessage').textContent='';const{error}=await supabaseClient.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)$('#authMessage').textContent=error.message});
$('#signUpBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<6){$('#authMessage').textContent='Enter an email and password (minimum 6 characters).';return}const{error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:AUTH_REDIRECT_URL}});$('#authMessage').textContent=error?error.message:'Account created. Check your email to confirm it.'};
$('#resendBtn').onclick=async()=>{const email=$('#email').value.trim();if(!email){$('#authMessage').textContent='Enter your email address first.';return}const{error}=await supabaseClient.auth.resend({type:'signup',email,options:{emailRedirectTo:AUTH_REDIRECT_URL}});$('#authMessage').textContent=error?error.message:'Confirmation email sent. Check your inbox and junk folder.'};
$('#signOutBtn').onclick=async()=>{pinUnlocked=false;await supabaseClient.auth.signOut()};$('#pinUnlockForm').onsubmit=async e=>{e.preventDefault();const pin=$('#pinUnlock').value,stored=localStorage.getItem(pinKey(currentUser.id));if(!stored||await pinHash(pin,currentUser.id)!==stored){$('#pinMessage').textContent='Incorrect PIN.';$('#pinUnlock').value='';return}pinUnlocked=true;$('#pinMessage').textContent='';$('#pinUnlock').value='';pinView.classList.add('hidden');appView.classList.remove('hidden');await loadJobs()};$('#usePasswordBtn').onclick=async()=>{pinUnlocked=false;await supabaseClient.auth.signOut();pinView.classList.add('hidden');authView.classList.remove('hidden')};$('#pinSettingsBtn').onclick=()=>{if(!currentUser)return;$('#newPin').value='';$('#confirmPin').value='';$('#pinSetupMessage').textContent='';$('#removePinBtn').classList.toggle('hidden',!localStorage.getItem(pinKey(currentUser.id)));pinDialog.showModal()};$('#closePinBtn').onclick=()=>pinDialog.close();$('#pinSetupForm').onsubmit=async e=>{e.preventDefault();const a=$('#newPin').value,b=$('#confirmPin').value;if(!/^\d{4}$/.test(a)){ $('#pinSetupMessage').textContent='PIN must be exactly 4 digits.';return}if(a!==b){$('#pinSetupMessage').textContent='PINs do not match.';return}localStorage.setItem(pinKey(currentUser.id),await pinHash(a,currentUser.id));pinDialog.close();alert('PIN access is now enabled on this device.')};$('#removePinBtn').onclick=()=>{if(!currentUser)return;localStorage.removeItem(pinKey(currentUser.id));pinDialog.close();alert('PIN access removed from this device.')};
async function loadJobs(){const{data,error}=await supabaseClient.from('jobs').select('*').order('scheduled_date',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false});if(error){jobsList.innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}jobs=data||[];render()}
function filtered(){const q=$('#searchInput').value.toLowerCase().trim(),status=$('#statusFilter').value,today=localDate();return jobs.filter(j=>{if(status&&j.status!==status)return false;if(quickFilter==='today'&&j.scheduled_date!==today)return false;if(quickFilter==='unscheduled'&&j.scheduled_date)return false;if(quickFilter==='completed'&&j.status!=='completed')return false;if(q&&!`${j.title} ${j.customer_name} ${j.suburb} ${j.address_line} ${j.description}`.toLowerCase().includes(q))return false;return true})}
function durationLabel(minutes){if(!minutes)return'';const h=minutes/60;return `${Number.isInteger(h)?h.toFixed(1):h} hr${h===1?'':'s'}`}
function render(){const today=localDate();$('#countAll').textContent=jobs.length;$('#countToday').textContent=jobs.filter(j=>j.scheduled_date===today&&j.status!=='completed').length;$('#countUnscheduled').textContent=jobs.filter(j=>!j.scheduled_date&&j.status!=='completed').length;$('#countCompleted').textContent=jobs.filter(j=>j.status==='completed').length;const rows=filtered();jobsList.innerHTML=rows.length?rows.map(j=>`<article class="job-card" data-id="${j.id}"><div class="job-top"><div><div class="job-title">${esc(j.title)}</div><div class="muted">${esc(j.customer_name||'No customer')}${j.suburb?` · ${esc(j.suburb)}`:''}</div></div><span class="chip">${esc(labelStatus(j.status))}</span></div><div class="chips">${j.scheduled_date?`<span class="chip">📅 ${esc(j.scheduled_date)}${j.scheduled_start?` ${esc(j.scheduled_start.slice(0,5))}`:''}</span>`:'<span class="chip">Unscheduled</span>'}${j.priority!=='normal'?`<span class="chip">${esc(j.priority)}</span>`:''}${j.estimated_minutes?`<span class="chip">⏱ ${durationLabel(j.estimated_minutes)}</span>`:''}</div></article>`).join(''):'<div class="empty">No jobs here yet.</div>';document.querySelectorAll('.job-card').forEach(c=>c.onclick=()=>openJob(jobs.find(j=>j.id===c.dataset.id)))}
$('#searchInput').oninput=render;$('#statusFilter').onchange=render;document.querySelectorAll('.stat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.stat').forEach(x=>x.classList.remove('active'));b.classList.add('active');quickFilter=b.dataset.filter;render()});
function openJob(j=null){$('#jobForm').reset();$('#jobId').value=j?.id||'';$('#jobDialogTitle').textContent=j?'Edit job':'New job';$('#deleteJobBtn').classList.toggle('hidden',!j);const fields={jobTitle:'title',customerName:'customer_name',customerPhone:'customer_phone',addressLine:'address_line',suburb:'suburb',postcode:'postcode',description:'description',notes:'notes',status:'status',priority:'priority',scheduledDate:'scheduled_date',scheduledStart:'scheduled_start'};if(j){for(const[id,key]of Object.entries(fields))$('#'+id).value=j[key]??'';$('#estimatedHours').value=j.estimated_minutes?String(j.estimated_minutes/60):''}else{$('#status').value='new';$('#priority').value='normal'}dialog.showModal()}
$('#newJobBtn').onclick=()=>openJob();$('#closeJobBtn').onclick=()=>dialog.close();$('#jobForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#jobId').value,hours=Number($('#estimatedHours').value)||0,payload={user_id:currentUser.id,title:$('#jobTitle').value.trim(),customer_name:$('#customerName').value.trim()||null,customer_phone:$('#customerPhone').value.trim()||null,address_line:$('#addressLine').value.trim()||null,suburb:$('#suburb').value.trim()||null,postcode:$('#postcode').value.trim()||null,description:$('#description').value.trim()||null,notes:$('#notes').value.trim()||null,status:$('#status').value,priority:$('#priority').value,scheduled_date:$('#scheduledDate').value||null,scheduled_start:$('#scheduledStart').value||null,estimated_minutes:hours?Math.round(hours*60):null};payload.completed_at=payload.status==='completed'?new Date().toISOString():null;const q=id?supabaseClient.from('jobs').update(payload).eq('id',id):supabaseClient.from('jobs').insert(payload);const{error}=await q;if(error){alert(error.message);return}dialog.close();await loadJobs()});$('#deleteJobBtn').onclick=async()=>{const id=$('#jobId').value;if(!id||!confirm('Delete this job?'))return;const{error}=await supabaseClient.from('jobs').delete().eq('id',id);if(error){alert(error.message);return}dialog.close();await loadJobs()};init();